<a href="https://colab.research.google.com/github/erbiaoger/code/blob/main/numpy%E4%BD%BF%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy使用


### numpy random 随机数

In [ ]:
import numpy as np

a = np.random.random()      # 生成0～1之间的随机数
print(a)
b = np.random.uniform()     # 生成均匀分布的随机数
print(b)
c = np.random.randn(3, 4)       # 标准正态的
print(c)
d = np.random.randint(4, 10)# 随机的整数
print(d)
e = np.random.normal()
print(e)
f = np.random.shuffle(c)
print(f)
g = np.random.seed()
print(g)
h = np.random.random_sample()
print(h)

0.6830469376607394
0.05923921251331332
[[-0.36531038 -0.52209184 -2.61642629 -0.6358267 ]
 [-0.05141207  0.05279701 -1.71352381 -0.0802811 ]
 [-0.40119287 -0.94113812 -1.02720711  1.36507345]]
8
0.28939528193375014
None
None
0.26626914835281434


### 创建特定形状的多维数组

In [ ]:
print(np.zeros((3, 4)))
print(np.ones((3, 4)))
print(np.empty((3, 4)))
a = np.ones((2, 5))
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.empty_like(a))
print(np.eye(5))            # 用于创建一个5x5的矩阵，对角线为1，其余为0
print('\n')
print(np.full((3, 5), 666))   # 用于创建一个3x5的元素全为666的数组，

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[666 666 666 666 666]
 [666 666 666 666 666]
 [666 666 666 666 666]]


### numpy 生成有序数组

In [ ]:
print(np.arange(10))
print(np.arange(2, 8))
print(np.arange(2, 10, 2))
print(np.arange(2, 10, 2, dtype=np.float32))

# np.linspace(start, stop,  num=50, endpoint=True, retstep=False, dtype=None)
# linspace可以根据输入的指定数据范围以及等份数量，自动生成一个线性等分向量， 其中endpoint(包含终点)默认为True，等分数量num默认为50。如果将retstep设置为 True，则会返回一个带步长的ndarray。

print(np.linspace(0, 1, 11))    # 包含 end 的数

print(np.logspace(0, 1, 11))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6 8]
[2. 4. 6. 8.]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[ 1.          1.25892541  1.58489319  1.99526231  2.51188643  3.16227766
  3.98107171  5.01187234  6.30957344  7.94328235 10.        ]


### 获取数据
![](https://raw.githubusercontent.com/erbiaoger/PicGo/main/img202209102117349.png)

In [ ]:
nd12 = np.random.rand(4, 4)
print(nd12)
print(nd12[0:2, :])
print(nd12[:, 2])
print(nd12[3:, 2:])
print(nd12[2::2, ::2])
print(nd12[::2, ::2]) 

a = np.arange(1, 25, dtype=float)
c1 = np.random.choice(a, size=(3, 4))

[[0.28183498 0.90231699 0.03055966 0.42221938]
 [0.73550602 0.34058612 0.78861452 0.48492191]
 [0.04873046 0.53677254 0.83629072 0.56583474]
 [0.87219076 0.95832725 0.53930989 0.37898881]]
[[0.28183498 0.90231699 0.03055966 0.42221938]
 [0.73550602 0.34058612 0.78861452 0.48492191]]
[0.03055966 0.78861452 0.83629072 0.53930989]
[[0.53930989 0.37898881]]
[[0.04873046 0.83629072]]
[[0.28183498 0.03055966]
 [0.04873046 0.83629072]]


### numpy 算术运算

In [ ]:
# numpy.multiply(x1, x2, /, out=None, *, where=True, casting=)
A = np.array([[1, 2], [-1, 4]])
B = np.array([[2, 0], [3, 4]])

print(np.multiply(A, B))
print(A * B)
print(np.dot(A, B))

[[ 2  0]
 [-3 16]]
[[ 2  0]
 [-3 16]]
[[ 8  8]
 [10 16]]


### 改变数组形状
![](https://raw.githubusercontent.com/erbiaoger/PicGo/main/img202209102159041.png)

In [ ]:
# reshape 不会修改向量本身
arr = np.arange(10)
print(arr)
print(arr.reshape(2, 5))
print(arr.reshape(5, -1))
print(arr.reshape(-1, 5))

# resize 会修改向量本身
arr = np.arange(10)
arr.resize(2, 5)
print(arr)

# .T 向量转置
arr = np.arange(12).reshape(3, 4)
print(arr)
print(arr.T)

# ravel 向量展平
arr = np.arange(6).reshape(2, -1)
print(arr)
print("按列优先，展平")
print(arr.ravel('F'))
print("按行优先，展平")
print(arr.ravel())

# flatten 矩阵转换为向量
a = np.floor(10*np.random.random((3, 4)))
print(a)
print(a.flatten())

# transpose 对高维矩阵进行轴对换，这个在深度学习中经常使用，比如把图片中表示颜色顺序的 RGB改为GBR
arr = np.arange(24).reshape(2, 3, 4)
print(arr.shape)
print(arr.transpose(1, 2, 0).shape) 

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 1 2]
 [3 4 5]]
按列优先，展平
[0 3 1 4 2 5]
按行优先，展平
[0 1 2 3 4 5]
[[5. 3. 9. 8.]
 [4. 5. 2. 8.]
 [1. 2. 1. 0.]]
[5. 3. 9. 8. 4. 5. 2. 8. 1. 2. 1. 0.]
(2, 3, 4)
(3, 4, 2)


### 合并数组
![](https://raw.githubusercontent.com/erbiaoger/PicGo/main/img202209110939897.png)

In [ ]:
# append
## 合并一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.append(a, b)
print(c)
## 合并多维数组
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
c = np.append(a, b, axis=0) # 按行合并
d = np.append(a, b, axis=1) # 按列合并
print(c, c.shape)
print(d, d.shape)

# concatenate 沿指定轴连接数组或矩阵
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b.T), axis=1)
print(c, '\n', d)

# stack 沿指定轴堆叠数组或矩阵
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), axis=0))

[1 2 3 4 5 6]
[[0 1]
 [2 3]
 [0 1]
 [2 3]] (4, 2)
[[0 1 0 1]
 [2 3 2 3]] (2, 4)
[[1 2]
 [3 4]
 [5 6]] 
 [[1 2 5]
 [3 4 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


![](https://raw.githubusercontent.com/erbiaoger/PicGo/main/img202209111025016.png)